INSERT INTO terms (term_id, title, content, is_required, is_active, created_at, updated_at)
VALUES
    (1, '만 14세 이상입니다 (필수)', '본 서비스는 만 14세 이상만 이용할 수 있습니다.', true, true, NOW(), NOW()),
    (2, '서비스 이용약관 동의 (필수)', '본 약관은 서비스 이용과 관련된 권리 및 의무를 규정합니다.', true, true, NOW(), NOW()),
    (3, '개인정보 수집 및 이용 동의 (필수)', '서비스 제공을 위해 개인정보를 수집 및 이용합니다.', true, true, NOW(), NOW()),
    (4, '광고 및 마케팅 정보 수신 동의 (선택)', '이벤트, 할인, 마케팅 정보를 수신할 수 있습니다.', false, true, NOW(), NOW())
    ON DUPLICATE KEY UPDATE
                         title = VALUES(title),
                         content = VALUES(content),
                         is_required = VALUES(is_required),
                         is_active = VALUES(is_active),
                         updated_at = NOW();

-- 가공/유제품
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('가다랑어포', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('누텔라', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('단무지', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('돈까스', 'PROCESSED_DAIRY', 'EACH', 0, NOW(), NOW()),
                                                                                   ('두유', 'PROCESSED_DAIRY', 'ML', 0, NOW(), NOW()),
                                                                                   ('딸기잼', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('땅콩버터', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('땅콩잼', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('라이스페이퍼', 'PROCESSED_DAIRY', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('만두', 'PROCESSED_DAIRY', 'EACH', 0, NOW(), NOW()),
                                                                                   ('맛살', 'PROCESSED_DAIRY', 'EACH', 0, NOW(), NOW()),
                                                                                   ('모짜렐라치즈', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('미트볼', 'PROCESSED_DAIRY', 'EACH', 0, NOW(), NOW()),
                                                                                   ('버터', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('부라타치즈', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('사과잼', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('생크림', 'PROCESSED_DAIRY', 'ML', 0, NOW(), NOW()),
                                                                                   ('아몬드우유', 'PROCESSED_DAIRY', 'ML', 0, NOW(), NOW()),
                                                                                   ('연유', 'PROCESSED_DAIRY', 'ML', 0, NOW(), NOW()),
                                                                                   ('요거트', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('요구르트', 'PROCESSED_DAIRY', 'ML', 0, NOW(), NOW()),
                                                                                   ('우유', 'PROCESSED_DAIRY', 'ML', 0, NOW(), NOW()),
                                                                                   ('체다치즈', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('초콜릿', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('치즈', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('크림치즈', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('통조림옥수수', 'PROCESSED_DAIRY', 'CAN', 0, NOW(), NOW()),
                                                                                   ('통조림참치', 'PROCESSED_DAIRY', 'CAN', 0, NOW(), NOW()),
                                                                                   ('통조림햄', 'PROCESSED_DAIRY', 'CAN', 0, NOW(), NOW()),
                                                                                   ('파마산치즈', 'PROCESSED_DAIRY', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('피자', 'PROCESSED_DAIRY', 'PAN', 0, NOW(), NOW()),
                                                                                   ('핫도그', 'PROCESSED_DAIRY', 'EACH', 0, NOW(), NOW()),
                                                                                   ('휘핑크림', 'PROCESSED_DAIRY', 'ML', 0, NOW(), NOW());

-- 육류/계란
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('계란', 'MEAT_EGG', 'EACH', 0, NOW(), NOW()),
                                                                                   ('국거리소고기', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('다진돼지고기', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('다진소고기', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('닭가슴살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('닭고기', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('닭날개', 'MEAT_EGG', 'EACH', 0, NOW(), NOW()),
                                                                                   ('닭다리', 'MEAT_EGG', 'EACH', 0, NOW(), NOW()),
                                                                                   ('대패삼겹살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('돼지 갈매기살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('돼지 뒷다리', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('돼지 등심', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('돼지 목살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('돼지 앞다리살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('돼지 항정상', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('베이컨', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('비엔나소세지', 'MEAT_EGG', 'EACH', 0, NOW(), NOW()),
                                                                                   ('삼겹살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소 등심', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소 안심', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소 채끝살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소고기', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소고기 갈비', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소고기 목살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소고기 사태', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소고기 앞다리살', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소고기 우둔', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소세지', 'MEAT_EGG', 'EACH', 0, NOW(), NOW()),
                                                                                   ('양고기', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('잠봉', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('차돌박이', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('햄', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('훈제오리', 'MEAT_EGG', 'GRAM', 0, NOW(), NOW());

-- 곡물/견과류
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('감자전분', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('검은깨', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('귀리', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('깨', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('녹두', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('두부', 'GRAIN_NUT', 'MO', 0, NOW(), NOW()),
                                                                                   ('들깨가루', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('땅콩', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('밀가루', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('밤', 'GRAIN_NUT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('백미', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('보리', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('부침가루', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('빵가루', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('순두부', 'GRAIN_NUT', 'PACK', 0, NOW(), NOW()),
                                                                                   ('시리얼', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('쌀가루', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('쌀밥', 'GRAIN_NUT', 'BOWL', 0, NOW(), NOW()),
                                                                                   ('아몬드', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('연두부', 'GRAIN_NUT', 'PACK', 0, NOW(), NOW()),
                                                                                   ('오트밀', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('옥수수', 'GRAIN_NUT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('완두콩', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('유부', 'GRAIN_NUT', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('잣', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('전분', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('찹쌀', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('치아씨드', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('코코넛', 'GRAIN_NUT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('콩', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('튀김가루', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('팥', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('피스타치오', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('헤이즐넛', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('현미', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('호두', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('흑미', 'GRAIN_NUT', 'GRAM', 0, NOW(), NOW());

-- 과일
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('감', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('곶감', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('귤', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('딸기', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('레몬', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('망고', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('매실', 'FRUIT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('멜론', 'FRUIT', 'HEAD', 0, NOW(), NOW()),
                                                                                   ('바나나', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('배', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('복숭아', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('불루베리', 'FRUIT', 'PACK', 0, NOW(), NOW()),
                                                                                   ('사과', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('샤인머스캣', 'FRUIT', 'BONG', 0, NOW(), NOW()),
                                                                                   ('수박', 'FRUIT', 'HEAD', 0, NOW(), NOW()),
                                                                                   ('오렌지', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('자두', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('자몽', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('체리', 'FRUIT', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('키위', 'FRUIT', 'EACH', 0, NOW(), NOW()),
                                                                                   ('파인애플', 'FRUIT', 'HEAD', 0, NOW(), NOW()),
                                                                                   ('포도', 'FRUIT', 'BONG', 0, NOW(), NOW()),
                                                                                   ('한라봉', 'FRUIT', 'EACH', 0, NOW(), NOW());

-- 면
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('당면', 'NOODLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('라면', 'NOODLE', 'BONG', 0, NOW(), NOW()),
                                                                                   ('메밀면', 'NOODLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('비빔면', 'NOODLE', 'BONG', 0, NOW(), NOW()),
                                                                                   ('소면', 'NOODLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('스파게티면', 'NOODLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('쌀국수면', 'NOODLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('우동면', 'NOODLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('짜장라면', 'NOODLE', 'BONG', 0, NOW(), NOW()),
                                                                                   ('쫄면', 'NOODLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('칼국수면', 'NOODLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('컵라면', 'NOODLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('파스타면', 'NOODLE', 'GRAM', 0, NOW(), NOW());

-- 빵/떡
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('가래떡', 'BREAD_CAKE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('떡', 'BREAD_CAKE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('떡국떡', 'BREAD_CAKE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('떡볶이떡', 'BREAD_CAKE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('또띠아', 'BREAD_CAKE', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('바게트', 'BREAD_CAKE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('베이글', 'BREAD_CAKE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('빵', 'BREAD_CAKE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('식빵', 'BREAD_CAKE', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('즉석밥', 'BREAD_CAKE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('치아바타', 'BREAD_CAKE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('케이크', 'BREAD_CAKE', 'SLICE', 0, NOW(), NOW());

-- 음료
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('감귤주스', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('망고주스', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('맥주', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('사이다', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('생수', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('소주', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('오렌지주스', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('제로콜라', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('콜라', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('탄산수', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('포도주스', 'BEVERAGE', 'ML', 0, NOW(), NOW()),
                                                                                   ('환타', 'BEVERAGE', 'ML', 0, NOW(), NOW());

-- 채소
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('가지', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('감자', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('고구마', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('고수', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('고추', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('깻잎', 'VEGETABLE', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('꽈리고추', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('냉이', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('단호박', 'VEGETABLE', 'HEAD', 0, NOW(), NOW()),
                                                                                   ('달래', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('당근', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('대파', 'VEGETABLE', 'STALK', 0, NOW(), NOW()),
                                                                                   ('두릅', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('딜', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('로즈마리', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('마늘쫑', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('무', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('미나리', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('바질', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('방울토마토', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('배추', 'VEGETABLE', 'POGI', 0, NOW(), NOW()),
                                                                                   ('버섯', 'VEGETABLE', 'BONG', 0, NOW(), NOW()),
                                                                                   ('봄동', 'VEGETABLE', 'POGI', 0, NOW(), NOW()),
                                                                                   ('부추', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('브로콜리', 'VEGETABLE', 'BONG', 0, NOW(), NOW()),
                                                                                   ('상추', 'VEGETABLE', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('샐러드', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('샐러리', 'VEGETABLE', 'STALK', 0, NOW(), NOW()),
                                                                                   ('생강', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('숙주', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('시금치', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('쑥', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('쑥갓', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('아보카도', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('아스파라거스', 'VEGETABLE', 'STALK', 0, NOW(), NOW()),
                                                                                   ('애플민트', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('애호박', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('양배추', 'VEGETABLE', 'POGI', 0, NOW(), NOW()),
                                                                                   ('양상추', 'VEGETABLE', 'POGI', 0, NOW(), NOW()),
                                                                                   ('양송이버섯', 'VEGETABLE', 'BONG', 0, NOW(), NOW()),
                                                                                   ('양파', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('연근', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('열무', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('오이', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('올리브', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('우엉', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('쪽파', 'VEGETABLE', 'STALK', 0, NOW(), NOW()),
                                                                                   ('청경채', 'VEGETABLE', 'POGI', 0, NOW(), NOW()),
                                                                                   ('청양고추', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('취나물', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('콩나물', 'VEGETABLE', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('토마토', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('파프리카', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('팽이버섯', 'VEGETABLE', 'BONG', 0, NOW(), NOW()),
                                                                                   ('표고버섯', 'VEGETABLE', 'BONG', 0, NOW(), NOW()),
                                                                                   ('피망', 'VEGETABLE', 'EACH', 0, NOW(), NOW()),
                                                                                   ('호박', 'VEGETABLE', 'EACH', 0, NOW(), NOW());

-- 해산물
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('가리비', 'SEAFOOD', 'EACH', 0, NOW(), NOW()),
                                                                                   ('갈치', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('고등어', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('골뱅이', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('굴', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('굴비', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('김', 'SEAFOOD', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('꼬막', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('꽁치', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('꽃게', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('낙지', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('도미', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('동태', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('멍게', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('멸치', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('명란젓', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('명태', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('문어', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('미역', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('바지락', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('삼치', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('새우', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소라', 'SEAFOOD', 'EACH', 0, NOW(), NOW()),
                                                                                   ('아귀', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('어묵', 'SEAFOOD', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('연어', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('오징어', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('오징어젓갈', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('장어', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('전복', 'SEAFOOD', 'EACH', 0, NOW(), NOW()),
                                                                                   ('전어', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('조개', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('조기', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('진미오징어', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('쭈꾸미', 'SEAFOOD', 'MARI', 0, NOW(), NOW()),
                                                                                   ('참다랑어', 'SEAFOOD', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('칵테일새우', 'SEAFOOD', 'GRAM', 0, NOW(), NOW());

-- 조미료/양념
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('겨자', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('고추냉이', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('고추장', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('고춧가루', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('국간장', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('굴소스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('까나리액젓', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('꿀', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('녹차가루', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('다시다', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('다시마', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('다진마늘', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('돈까스소스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('된장', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('들기름', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('레몬즙', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('마라소스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('마요네즈', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('맛술', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('매실청', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('머스타드', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('메이플시럽', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('멸치액젓', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('물엿', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('미소된장', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('바질페스토', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('살사소스', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('새우젓', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('설탕', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('소금', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('스리라차소스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('스테비아', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('스테이크소스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('식용유', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('식초', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('쌈장', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('알룰로스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('양조간장', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('연겨자', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('연두', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('올리고당', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('올리브유', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('우스타소스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('조청', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('진간장', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('참기름', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('참치액젓', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('청국장', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('청주', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('초고추장', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('칠리소스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('카라멜시럽', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('카레분말', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('케찹', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('타르타르소스', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('통후추', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('파슬리', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('페페로치노', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('핫소스', 'SEASONING', 'ML', 0, NOW(), NOW()),
                                                                                   ('홀그레인머스타드', 'SEASONING', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('후추', 'SEASONING', 'GRAM', 0, NOW(), NOW());

-- 간식
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('감자칩', 'SNACK', 'BONG', 0, NOW(), NOW()),
                                                                                   ('과자', 'SNACK', 'BONG', 0, NOW(), NOW()),
                                                                                   ('사탕', 'SNACK', 'EACH', 0, NOW(), NOW()),
                                                                                   ('젤리', 'SNACK', 'BONG', 0, NOW(), NOW()),
                                                                                   ('쿠키', 'SNACK', 'EACH', 0, NOW(), NOW()),
                                                                                   ('크래커', 'SNACK', 'PIECE', 0, NOW(), NOW()),
                                                                                   ('팝콘', 'SNACK', 'BONG', 0, NOW(), NOW());

-- 기타
INSERT INTO ingredients (name, category, unit, weight, created_at, updated_at) VALUES
                                                                                   ('김치', 'ETC', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('깍두기', 'ETC', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('묵은지', 'ETC', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('백김치', 'ETC', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('열무김치', 'ETC', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('총각김치', 'ETC', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('파김치', 'ETC', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('피클', 'ETC', 'GRAM', 0, NOW(), NOW()),
                                                                                   ('할라피뇨', 'ETC', 'GRAM', 0, NOW(), NOW());

-- 세부 카테고리 초기화 (한식: 1~10, 중식: 11~20, 일식: 21~30, 양식: 31~40, 동남아: 41~50)
INSERT INTO categories (name, type, created_at, updated_at) VALUES
-- 한식
('국·찌개', 'DISH_TYPE', NOW(), NOW()),
('밥요리', 'DISH_TYPE', NOW(), NOW()),
('국수', 'DISH_TYPE', NOW(), NOW()),
('볶음', 'DISH_TYPE', NOW(), NOW()),
('조림', 'DISH_TYPE', NOW(), NOW()),
('전·부침', 'DISH_TYPE', NOW(), NOW()),
('구이', 'DISH_TYPE', NOW(), NOW()),
('비빔·무침', 'DISH_TYPE', NOW(), NOW()),
('반찬', 'DISH_TYPE', NOW(), NOW()),
('김치 요리', 'DISH_TYPE', NOW(), NOW()),

-- 중식
('면요리', 'DISH_TYPE', NOW(), NOW()),
('볶음밥', 'DISH_TYPE', NOW(), NOW()),
('덮밥', 'DISH_TYPE', NOW(), NOW()),
('볶음', 'DISH_TYPE', NOW(), NOW()),
('튀김', 'DISH_TYPE', NOW(), NOW()),
('국물 요리', 'DISH_TYPE', NOW(), NOW()),
('마라 요리', 'DISH_TYPE', NOW(), NOW()),
('고기 요리', 'DISH_TYPE', NOW(), NOW()),
('해물 요리', 'DISH_TYPE', NOW(), NOW()),
('만두 요리', 'DISH_TYPE', NOW(), NOW()),

-- 일식
('덮밥', 'DISH_TYPE', NOW(), NOW()),
('면요리', 'DISH_TYPE', NOW(), NOW()),
('국물', 'DISH_TYPE', NOW(), NOW()),
('볶음', 'DISH_TYPE', NOW(), NOW()),
('조림', 'DISH_TYPE', NOW(), NOW()),
('튀김', 'DISH_TYPE', NOW(), NOW()),
('구이', 'DISH_TYPE', NOW(), NOW()),
('도시락', 'DISH_TYPE', NOW(), NOW()),
('해물 요리', 'DISH_TYPE', NOW(), NOW()),
('계란 요리', 'DISH_TYPE', NOW(), NOW()),

-- 양식
('파스타', 'DISH_TYPE', NOW(), NOW()),
('리조또', 'DISH_TYPE', NOW(), NOW()),
('볶음', 'DISH_TYPE', NOW(), NOW()),
('스테이크', 'DISH_TYPE', NOW(), NOW()),
('오븐 요리', 'DISH_TYPE', NOW(), NOW()),
('샐러드', 'DISH_TYPE', NOW(), NOW()),
('수프', 'DISH_TYPE', NOW(), NOW()),
('브런치', 'DISH_TYPE', NOW(), NOW()),
('피자', 'DISH_TYPE', NOW(), NOW()),
('치즈 요리', 'DISH_TYPE', NOW(), NOW()),

-- 동남아
('밥요리', 'DISH_TYPE', NOW(), NOW()),
('쌀국수', 'DISH_TYPE', NOW(), NOW()),
('면요리', 'DISH_TYPE', NOW(), NOW()),
('국물', 'DISH_TYPE', NOW(), NOW()),
('볶음', 'DISH_TYPE', NOW(), NOW()),
('튀김', 'DISH_TYPE', NOW(), NOW()),
('커리 요리', 'DISH_TYPE', NOW(), NOW()),
('고기 요리', 'DISH_TYPE', NOW(), NOW()),
('해물 요리', 'DISH_TYPE', NOW(), NOW()),
('샐러드', 'DISH_TYPE', NOW(), NOW());

-- 레시피 더미 데이터 (한식 - 국/찌개)
INSERT INTO recipes (title, level, rating_count, time, cooking_time, channel, channel_id, views, image_url, category, video_id, video_url, created_at, updated_at) VALUES
('얼큰한 김치찌개', 3, 120, '10:30', 20, '백종원 PAIK JONG WON', 'UCyn-K7rZLXjGl7VXGweIlcA', 500000, 'https://i.ytimg.com/vi/PjLh_2sQxXg/maxresdefault.jpg', 'KOREAN', 'PjLh_2sQxXg', 'https://www.youtube.com/watch?v=PjLh_2sQxXg', NOW(), NOW()),
('참치 김치찌개', 2, 85, '08:15', 15, '하루한끼 one meal a day', 'UC_b4Od88hM7h56N0a4t7Q', 300000, 'https://i.ytimg.com/vi/abc12345/maxresdefault.jpg', 'KOREAN', 'abc12345', 'https://www.youtube.com/watch?v=abc12345', NOW(), NOW()),
('돼지고기 김치찌개', 3, 200, '12:00', 25, '성시경 SUNG SI KYUNG', 'UC7-8-9-0', 800000, 'https://i.ytimg.com/vi/def67890/maxresdefault.jpg', 'KOREAN', 'def67890', 'https://www.youtube.com/watch?v=def67890', NOW(), NOW()),
('스팸 김치찌개', 1, 50, '07:45', 15, '자취요리신', 'UC1-2-3-4', 150000, 'https://i.ytimg.com/vi/ghi12345/maxresdefault.jpg', 'KOREAN', 'ghi12345', 'https://www.youtube.com/watch?v=ghi12345', NOW(), NOW()),
('꽁치 김치찌개', 4, 30, '15:20', 30, '어남선생', 'UC5-6-7-8', 100000, 'https://i.ytimg.com/vi/jkl67890/maxresdefault.jpg', 'KOREAN', 'jkl67890', 'https://www.youtube.com/watch?v=jkl67890', NOW(), NOW()),
('된장찌개', 3, 150, '11:10', 20, '백종원 PAIK JONG WON', 'UCyn-K7rZLXjGl7VXGweIlcA', 600000, 'https://i.ytimg.com/vi/mno12345/maxresdefault.jpg', 'KOREAN', 'mno12345', 'https://www.youtube.com/watch?v=mno12345', NOW(), NOW()),
('차돌 된장찌개', 4, 90, '13:40', 25, '성시경 SUNG SI KYUNG', 'UC7-8-9-0', 400000, 'https://i.ytimg.com/vi/pqr67890/maxresdefault.jpg', 'KOREAN', 'pqr67890', 'https://www.youtube.com/watch?v=pqr67890', NOW(), NOW()),
('순두부찌개', 3, 110, '09:50', 20, '하루한끼 one meal a day', 'UC_b4Od88hM7h56N0a4t7Q', 350000, 'https://i.ytimg.com/vi/stu12345/maxresdefault.jpg', 'KOREAN', 'stu12345', 'https://www.youtube.com/watch?v=stu12345', NOW(), NOW()),
('부대찌개', 3, 180, '14:20', 30, '백종원 PAIK JONG WON', 'UCyn-K7rZLXjGl7VXGweIlcA', 700000, 'https://i.ytimg.com/vi/vwx67890/maxresdefault.jpg', 'KOREAN', 'vwx67890', 'https://www.youtube.com/watch?v=vwx67890', NOW(), NOW()),
('콩나물국', 1, 40, '06:30', 15, '자취요리신', 'UC1-2-3-4', 120000, 'https://i.ytimg.com/vi/yz12345/maxresdefault.jpg', 'KOREAN', 'yz12345', 'https://www.youtube.com/watch?v=yz12345', NOW(), NOW()),
('미역국', 2, 130, '10:00', 25, '성시경 SUNG SI KYUNG', 'UC7-8-9-0', 550000, 'https://i.ytimg.com/vi/AB12345/maxresdefault.jpg', 'KOREAN', 'AB12345', 'https://www.youtube.com/watch?v=AB12345', NOW(), NOW()),
('소고기 무국', 3, 100, '12:15', 30, '어남선생', 'UC5-6-7-8', 450000, 'https://i.ytimg.com/vi/CD67890/maxresdefault.jpg', 'KOREAN', 'CD67890', 'https://www.youtube.com/watch?v=CD67890', NOW(), NOW());

-- 레시피-카테고리 매핑 (국/찌개: ID 1)
INSERT INTO recipe_categories (recipe_id, category_id, created_at, updated_at) VALUES
(1, 1, NOW(), NOW()),
(2, 1, NOW(), NOW()),
(3, 1, NOW(), NOW()),
(4, 1, NOW(), NOW()),
(5, 1, NOW(), NOW()),
(6, 1, NOW(), NOW()),
(7, 1, NOW(), NOW()),
(8, 1, NOW(), NOW()),
(9, 1, NOW(), NOW()),
(10, 1, NOW(), NOW()),
(11, 1, NOW(), NOW()),
(12, 1, NOW(), NOW());
